labels = {
    "No clasificado": 0,
    "Suelo": 1,
    "Vegetación": 2,
    "Edificaciones": 3,
    "Postes BT": 4,
    "Cables BT": 5,
    "Postes MT": 6,
    "Cables MT": 7,
    "Postes AT": 8,
    "Cables AT": 9,
    "Anuncios": 10,
    "Escombros": 11,
    "Andamios": 12,
    "Escaleras": 13,
    "Ladrillos": 14,
    "Trabajos eléctricos MT": 15,
    "Cables MT 1": 21,
    "Cables MT 2": 22,
    "Cables MT 3": 23,
}
